---
title: "FileMaker2openBIS"
output: html_notebook
---

```{r, include=FALSE}
library(tidyverse)
library(stringr)
```

# Files
```{r}
path = "/Volumes/huber.michael/Repositories/DMS/FileMaker2openBIS/"
FileMakerRunsFile = paste0(path, "FileMakerRuns.csv")
FileMakerSamplesFile = paste0(path, "FileMakerSamples.csv")

```

# FileMaker Runs
```{r, echo=FALSE, message=FALSE}
FileMakerRuns = read_csv(FileMakerRunsFile, col_names = FALSE) %>%
        rename(DATE = X1,
               INVESTIGATOR_NAME = X2,
               ACCOUNT = X3,
               EXPERIMENT_NAME = X4,
               DESCRIPTION = X5,
               SAMPLE_SHEET_NAME = X6,
               RUN_NAME = X7,
               samples = X8,
               PHIX_CONCENTRATION = X9,
               RGT_BOX_1 = X10,
               RGT_BOX_2 = X11,
               READ_1 = X12,
               READ_2 = X13,
               kit = X14) %>%
        
        filter(!(grepl("Extern", ACCOUNT))) %>%
        filter(!(RUN_NAME %in% c("170614_M01274_0189_000000000-B4FF4", "170621_M02081_0217_000000000-B4FP7", "170622_M01274_0190_000000000-B4FPY"))) %>% ### exclude already imported runs
        
        mutate(new_project = case_when(
                RUN_NAME %in% c ("121219_M01274_0002_000000000-A2DWH") ~ "OTHER", ### set project of individiual runs
                RUN_NAME %in% c ("140408_M01274_0071_000000000-A8CRD", "140616_M01274_0080_000000000-A8H02","141021_M01274_0095_000000000-A8CPG",
                                 "151123_M01274_0137_000000000-AH9KY", "151130_M01274_0138_000000000-AJKD7", "151222_M02081_0125_000000000-AJMJB",
                                 "160105_M01274_0140_000000000-AJGE4", "160301_M01274_0147_000000000-AJKD5", "160309_M01274_0148_000000000-AJKPC",
                                 "160706_M01274_0158_000000000-AMAWD", "160908_M01274_0164_000000000-AMT73", "161017_M01274_0166_000000000-AT5LA") ~ "METAGENOMICS", ### set project of individiual runs
                RUN_NAME %in% c ("160315_M02081_0139_000000000-AL4VW", "160420_M02081_0147_000000000-AL55K") ~ "PLASMIDS", ### set project of individiual runs
                ACCOUNT == "KFSP Virome" ~ "METAGENOMICS",
                INVESTIGATOR_NAME == "Merle Schanz" ~ "ANTIBODIES",
                INVESTIGATOR_NAME == "Cyril Shah" ~ "RESISTANCE",
                INVESTIGATOR_NAME == "Natacha Espirito Santo" ~ "PLASMIDS",
                TRUE ~ "OTHER"
                )) %>%
        
        mutate(identifier = paste0("/IMV/", RUN_NAME,"_", new_project),
               DATE = gsub("\\.", "\\/", DATE),
               DATE = as.Date(DATE, format = "%d/%m/%Y"),
               container = "",
               parents = "",
               experiment = paste0("/IMV/", new_project,"/MISEQ_RUNS"),
               default_space = "IMV",
               MISEQ_WORKFLOW = "",
               APPLICATION = "",
               ASSAY = "",
               CHEMISTRY = "",
               RGT_BOX_1 = paste0("RGT", RGT_BOX_1),
               RGT_BOX_2 = paste0("RGT", RGT_BOX_2),
               tags = "FileMaker") %>%
        
        select(identifier, experiment, default_space, INVESTIGATOR_NAME, EXPERIMENT_NAME, RUN_NAME, SAMPLE_SHEET_NAME, ACCOUNT, DATE,
               MISEQ_WORKFLOW, APPLICATION, ASSAY, DESCRIPTION, CHEMISTRY, READ_1, READ_2, PHIX_CONCENTRATION, RGT_BOX_1, RGT_BOX_2, tags)

FileMakerRuns[is.na(FileMakerRuns)] = ""

FileMakerRuns
```
### Write runs upload file
```{r, echo=FALSE, message=FALSE}
FileMakerRuns %>%   
        #filter(substr(RUN_NAME, 1, 2) == "17") %>% ### filter for year
        write_tsv(., paste0(path, "SAMPLE_MISEQ-RUN.tsv"))
```

# FileMaker Samples
```{r, echo=FALSE, message=FALSE}
FileMakerSamples = read_csv(FileMakerSamplesFile, col_names = FALSE) %>%
        rename(RUN_NAME = X1,
               sample_sheet = X2,
               SAMPLE_ID = X3,
               SAMPLE_NAME = X4,
               DESCRIPTION = X5,
               I7_INDEX_ID = X6,
               I5_INDEX_ID = X7,
               sample_project = X8) %>%

        mutate(SAMPLE_NAME = ifelse((!(is.na(as.numeric(SAMPLE_ID)) | as.numeric(SAMPLE_ID) > 96)), SAMPLE_NAME, paste(SAMPLE_NAME,SAMPLE_ID))) %>%
        mutate(SAMPLE_NAME = sub("NA ", "", SAMPLE_NAME)) %>%
        mutate(id_from_id = ifelse((!(is.na(as.numeric(SAMPLE_ID)) | as.numeric(SAMPLE_ID) > 96)), SAMPLE_ID, NA)) %>%
        mutate(id_from_name = str_extract(str_extract(SAMPLE_NAME, "_S[0-9]+_L"), "[0-9]+")) %>%
        group_by(sample_sheet) %>%
        mutate(id_by_ss = row_number()) %>%
        mutate(final_id = case_when(
                RUN_NAME %in% c ("130527_M01274_0019_000000000-A3PTY", "130222_M01274_0007_000000000-A3FTH") ~ as.character(id_by_ss), ### set final_id of individiual runs
                !(is.na(id_from_name)) ~ id_from_name,
                !(is.na(id_from_id)) ~ id_from_id,
                TRUE ~ as.character(id_by_ss)
                )) %>%
        mutate(SAMPLE_ID = final_id) %>%
        
        right_join(., FileMakerRuns[, c("RUN_NAME", "experiment")], by = "RUN_NAME") %>% ### right_join samples to only inlcuded runs
        
        mutate(identifier = paste0("/IMV/", RUN_NAME,"-", SAMPLE_ID),
               container = "",
               parents = paste0(RUN_NAME,"_", unlist(strsplit(experiment, "/"))[3]),
               experiment = sub("/MISEQ_RUNS", "/MISEQ_SAMPLES", experiment),
               default_space = "IMV",
               SAMPLE_PLATE = "",
               SAMPLE_WELL = "",
               INDEX_1 = "",
               INDEX_2 = "",
               tags = "FileMaker") %>%
        
        ungroup %>%
        select(identifier, parents, experiment, default_space, SAMPLE_ID, SAMPLE_NAME, SAMPLE_PLATE, SAMPLE_WELL, INDEX_1, INDEX_2, I7_INDEX_ID, I5_INDEX_ID, DESCRIPTION, tags)

FileMakerSamples[is.na(FileMakerSamples)] = ""

FileMakerSamples
```

### Write samples upload file
```{r, echo=FALSE, message=FALSE}
FileMakerSamples %>%   
        #filter(substr(parents, 1, 2) == "17") %>% ### filter for year
        write_tsv(., paste0(path, "SAMPLE_MISEQ-SAMPLE.tsv"))
```
